paths:
  .github/workflows/python.yml:
    ignore:
      # job.workflow_repository / job.workflow_sha (September 2026) aren't known to actionlint yet.
      - 'property "workflow_(repository|sha)" is not defined'
